import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
    en: {
        translation: {
            "welcome": "Welcome!",
            "welcome_long": "Welcome to my web page!",
            "let's_start": "Let's start!",
            "about_me": "About me!",
            "about_me_long": "I'm Oussama Zazou Abid, also known as Zaos. I'm a Full Stack Developer with experience in frameworks such as React, Laravel, NodeJS, and VueJS. I have worked on bug resolution, process automation, and feature development in agile environments. My focus is on efficiency, teamwork, and delivering high-quality projects.",
            "education": "Education Background",
            "education_1": "Cross play Application Development",
            "education_2": "Web Applications Development",
            "education_3": "Microcomputer Systems & Network Technician",
            "education_4": "Compulsory Secondary Education",
            "my_experience": "My Experience!",
            "experience_1": "Data Analyst",
            "fun__exp1_1": "Working with AI",
            "fun__exp1_2": "Data Analysis",
            "fun__exp1_3": "Data Review",
            "experience_2": "Night Stocker",
            "fun__exp2_1": "Place products",
            "fun__exp2_2": "Stock Review",
            "fun__exp2_3": "Add new products",
            "fun__exp2_4": "Branding First",
            "experience_3": "Web Developer",
            "fun__exp3_1": "Place products",
            "experience_4": "FS Developer",
            "fun__exp4_1": "App Maintenance",
            "fun__exp4_2": "New Features",
            "experience_5": "Web Designer",
            "worked_with": "Worked with",
            "my_resume": "My Resume!",
        }
    },
    es: {
        translation: {
            "welcome": "¡Bienvenido!",
            "welcome_long": "¡Bienvenido a mi página web!",
            "let's_start": "¡Vamos a empezar!",
            "about_me": "¡Sobre mí!",
            "about_me_long": "Soy Oussama Zazou Abid, también conocido como Zaos. Soy un Desarrollador Full Stack con experiencia en frameworks como React, Laravel, NodeJS y VueJS. He trabajado en la resolución de errores, la automatización de procesos y el desarrollo de funciones en entornos ágiles. Mi enfoque está en la eficiencia, el trabajo en equipo y la entrega de proyectos de alta calidad.",
            "education": "Formación Académica",
            "education_1": "Desarrollo de Aplicaciones Cross Play",
            "education_2": "Desarrollo de Aplicaciones Web",
            "education_3": "Técnico en Sistemas Microinformáticos y Redes",
            "education_4": "Educación Secundaria Obligatoria",
            "my_experience": "¡Mi Experiencia!",
            "experience_1": "Analista de Datos",
            "fun__exp1_1": "Trabajo con IA",
            "fun__exp1_2": "Análisis de Datos",
            "fun__exp1_3": "Revisión de Datos",
            "experience_2": "Reponedor Nocturno",
            "fun__exp2_1": "Colocar productos",
            "fun__exp2_2": "Revisión de Stock",
            "fun__exp2_3": "Añadir nuevos productos",
            "fun__exp2_4": "Primero Branding",
            "experience_3": "Desarrollador Web",
            "fun__exp3_1": "Colocar productos",
            "experience_4": "Desarrollador FS",
            "fun__exp4_1": "Mantenimiento de Aplicaciones",
            "fun__exp4_2": "Nuevas Funcionalidades",
            "experience_5": "Diseñador Web",
            "worked_with": "Trabajado con",
            "my_resume": "¡Mi Currículum!",
        }
    },
    ca: {
        translation: {
            "welcome": "Benvingut!",
            "welcome_long": "Benvingut a la meva pàgina web!",
            "let's_start": "Comencem!",
            "about_me": "Sobre mi!",
            "about_me_long": "Sóc Oussama Zazou Abid, també conegut com Zaos. Sóc un Desenvolupador Full Stack amb experiència en frameworks com React, Laravel, NodeJS i VueJS. He treballat en la resolució d'errors, l'automatització de processos i el desenvolupament de funcionalitats en entorns àgils. El meu enfocament es basa en l'eficiència, el treball en equip i la lliurament de projectes d'alta qualitat.",
            "education": "Formació Acadèmica",
            "education_1": "Desenvolupament d'Aplicacions Cross Play",
            "education_2": "Desenvolupament d'Aplicacions Web",
            "education_3": "Tècnic en Sistemes Microinformàtics i Xarxes",
            "education_4": "Educació Secundària Obligatòria",
            "my_experience": "La meva Experiència!",
            "experience_1": "Analista de Dades",
            "fun__exp1_1": "Treballant amb IA",
            "fun__exp1_2": "Anàlisi de Dades",
            "fun__exp1_3": "Revisió de Dades",
            "experience_2": "Reposador Nocturn",
            "fun__exp2_1": "Col·locar productes",
            "fun__exp2_2": "Revisió d'Stock",
            "fun__exp2_3": "Afegir nous productes",
            "fun__exp2_4": "Marca Primer",
            "experience_3": "Desenvolupador Web",
            "fun__exp3_1": "Col·locar productes",
            "experience_4": "Desenvolupador FS",
            "fun__exp4_1": "Manteniment d'Aplicacions",
            "fun__exp4_2": "Noves Funcionalitats",
            "experience_5": "Dissenyador Web",
            "worked_with": "Treballat amb",
            "my_resume": "El meu Currículum!",
        }
    },
    de: {
        translation: {
            "welcome": "Willkommen!",
            "welcome_long": "Willkommen auf meiner Webseite!",
            "let's_start": "Lass uns anfangen!",
            "about_me": "Über mich!",
            "about_me_long": "Ich bin Oussama Zazou Abid, auch bekannt als Zaos. Ich bin ein Full Stack Developer mit Erfahrung in Frameworks wie React, Laravel, NodeJS und VueJS. Ich habe an der Fehlerbehebung, Prozessautomatisierung und der Entwicklung von Funktionen in agilen Umgebungen gearbeitet. Mein Fokus liegt auf Effizienz, Teamarbeit und der Lieferung hochwertiger Projekte.",
            "education": "Bildungshintergrund",
            "education_1": "Cross-Play-Anwendungsentwicklung",
            "education_2": "Webanwendungsentwicklung",
            "education_3": "Techniker für Mikrosysteme und Netzwerke",
            "education_4": "Pflichtschulbildung",
            "my_experience": "Meine Erfahrung!",
            "experience_1": "Datenanalyst",
            "fun__exp1_1": "Arbeiten mit KI",
            "fun__exp1_2": "Datenanalyse",
            "fun__exp1_3": "Datenprüfung",
            "experience_2": "Nachtschichtmitarbeiter",
            "fun__exp2_1": "Produkte platzieren",
            "fun__exp2_2": "Bestandsprüfung",
            "fun__exp2_3": "Neue Produkte hinzufügen",
            "fun__exp2_4": "Branding Zuerst",
            "experience_3": "Webentwickler",
            "fun__exp3_1": "Produkte platzieren",
            "experience_4": "FS-Entwickler",
            "fun__exp4_1": "App-Wartung",
            "fun__exp4_2": "Neue Funktionen",
            "experience_5": "Webdesigner",
            "worked_with": "Arbeitet mit",
            "my_resume": "Mein Lebenslauf!",
        }
    },
};

i18n.use(initReactI18next).init({
    resources,
    lng: "en",
    keySeparator: false,
    interpolation: {
        escapeValue: false
    }
});

export default i18n;
